{{- if and (eq .Values.storage.type "filesystem") .Values.storage.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mess-exchange.fullname" . }}-data
  labels:
    {{- include "mess-exchange.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.persistence.accessMode }}
  {{- if .Values.storage.persistence.storageClass }}
  storageClassName: {{ .Values.storage.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.persistence.size }}
{{- end }}
